/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_bamfile_free: (a: number, b: number) => void;
export const __wbg_chromatiqengine_free: (a: number, b: number) => void;
export const __wbg_vcffile_free: (a: number, b: number) => void;
export const bamfile_calculate_coverage: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const bamfile_generate_pileup: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number];
export const bamfile_get_read_count: (a: number) => bigint;
export const bamfile_get_reference_names: (a: number) => [number, number];
export const bamfile_new: (a: number, b: number) => [number, number, number];
export const chromatiqengine_calculate_combined_coverage: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const chromatiqengine_get_all_variants: (a: number) => [number, number, number];
export const chromatiqengine_get_bam_file_count: (a: number) => number;
export const chromatiqengine_get_vcf_file_count: (a: number) => number;
export const chromatiqengine_load_bam: (a: number, b: number, c: number) => [number, number, number];
export const chromatiqengine_load_vcf: (a: number, b: number, c: number) => [number, number, number];
export const chromatiqengine_new: () => number;
export const chromatiqengine_unload_bam: (a: number, b: number) => [number, number];
export const chromatiqengine_unload_vcf: (a: number, b: number) => [number, number];
export const get_capabilities: () => [number, number];
export const get_info: () => [number, number];
export const get_version: () => [number, number];
export const vcffile_get_high_quality_variants: (a: number, b: number) => [number, number, number];
export const vcffile_get_passed_variants: (a: number) => [number, number, number];
export const vcffile_get_stats: (a: number) => [number, number, number];
export const vcffile_get_variants: (a: number) => [number, number, number];
export const vcffile_get_variants_in_region: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const vcffile_new: (a: number, b: number) => [number, number, number];
export const init: () => void;
export const bamfile_get_region_stats: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
